load("@io_bazel_rules_go//proto:go_proto_library.bzl", "go_proto_library")

go_proto_library(
    name = "ticktacktoe_proto",
    srcs = ["ticktacktoe.proto"],
    has_services = 1,
    visibility = ["//visibility:public"],
)
